name: Build all
on:
  push:
    branches:
      - 'release/bbl-*'
  workflow_dispatch:
concurrency:
  group: bbl-build-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build_windows:
    name: Build Windows x64
    uses: ./.github/workflows/build_check_cache.yml
    with:
      os: windows-latest
      arch: x64
      build-deps-only: false
      force-build: false
    secrets: inherit
